server:
  servlet:
    context-path: /client-pet/api

spring:
  application:
    name: petz-be-challenge

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
       format_sql: true
